FROM python:3.10.10-alpine3.17

WORKDIR /app

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev nano
RUN pip install --upgrade pip

COPY app/ .
RUN pip install -r requirements.txt
RUN cd hotel_business && pip install .

EXPOSE 8000

CMD python3 /app/main.py